# Generated by Django 4.2.7 on 2023-11-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskDesc', models.CharField(max_length=1000)),
                ('priority', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
