# Generated by Django 4.2.7 on 2023-12-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskDesc',
            field=models.CharField(max_length=100),
        ),
    ]
