# Generated by Django 4.2.7 on 2023-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_tasks_priority_remove_tasks_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='id',
        ),
        migrations.AddField(
            model_name='tasks',
            name='sno',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
