# Generated by Django 4.2.7 on 2023-12-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_remove_tasks_id_tasks_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
